export default {
    HOME_WEBSITE_TITLE: "BloothForAlexa Developer",
    HOME_WEBSITE_HOME: "Home",
    HOME_ENTER: "Enter",
    HOME_CUSTOMIZATION: "Customize",
    HOME_CUSTOMIZATION_SUBTITLE: "Tools to help build customize iOS & Android app",
    HOME_AVS_ACCOUNT_ASSISTANT: "AVS Assistant",
    HOME_AVS_ACCOUNT_ASSISTANT_SUBTITLE: "Help to generate necessary information to use AVS.",
    LOGIN_ACCOUNT: "Account",
    LOGIN_PASS: "Password",
    LOGIN_CHANGE_PASS: "Change Password",
    LOGIN_CHANGE_LANGUAGE: "Change Language",
    LOGIN_SIGNIN: "Login",
    LOGIN_SUBMIT: "Submit",
    LOGIN_ACCOUNT_EMPTY: "Account or password is empty.",
    LOGIN_PASS_LENGTH_TOO_SHORT: "Password should more than 6 characters.",
    LOGIN_PASS_LENGTH_TOO_LONG: "Password should less than 16 characters.",
    LOGIN_PASS_INVALID: "Password should should only contain letters and numbers",
    LOGIN_ENTER_NECESSARY_HINT: "Please enter the following information to continue",
    LOGIN_COMPANY_HINT:
        "Company abbreviation, more than 3 and less than 10 characters, can only contain lower-case letters and numbers.",
    LOGIN_COMPANY_INVALID: "The format of Company abbreviation invalid.",
    LOGIN_EMAIL_HINT: "Email",
    LOGIN_RESET_HINT: "For you login first time, please reset your password which is 6-16 letters and numbers.",
    LOGIN_EMAIL_INVALID: "The format of email invalid.",
    LOGIN_COMPANY_TOOSHORT: "Company abbreviation needs more than 3 characters.",
    LOGIN_COMPANY_TOOLONG: "Company abbreviation needs less than 3 characters.",
    AMAZON_ACCOUNT_MANAGEMENT: "Product Management",
    AMAZON_BUILD: "Build",
    AMAZON_ACCOUNT_START: "Start",
    AMAZON_ACCOUNT_CONTINUE: "Continue",
    AMAZON_ACCOUNT_FINISH: "Finish",
    AMAZON_ACCOUNT_NEW: "New",
    AMAZON_ACCOUNT_NO_APIKEYS: "You need to register apikeys to use AVS",
    AMAZON_ACCOUNT_PRODUCT: "Product ID",
    AMAZON_ACCOUNT_PRODUCT_BETA: "Beta ID",
    AMAZON_ACCOUNT_ANDROID_PACKAGE: "Package",
    AMAZON_ACCOUNT_API_KEY: "API key",
    AMAZON_ACCOUNT_IOS_BUNDLEID: "Bundle ID",
    AMAZON_ACCOUNT_SUBMIT: "Submit",
    AMAZON_ACCOUNT_GET: "Get",
    AMAZON_ACCOUNT_CONFIRM: "Confirm",
    AMAZON_ACCOUNT_OFFICIAL_ID_REGISTRATION: "Official ID Registration",
    AMAZON_ACCOUNT_SECURITY_PROFILE: "Security Profile",
    AMAZON_ACCOUNT_PREWORK_AVS_CERTIFICATION: "Pre-work for AVS Certification",
    AMAZON_ACCOUNT_BETA_ID_REGISTRATION: "BETA ID Registration",
    AMAZON_ACCOUNT_MD5_NOTE2:
        'Click and copy the md5 and sha256 code below, and enter them to the corresponding textfields on the Amazon website, then click the "Generate New Key".',
    AMAZON_ACCOUNT_MD5_NOTE1: "Now, click the button on the right to get the MD5 signature and sha256 signature.",
    AMAZON_ACCOUNT_PRODUCTID_NOTE2:
        "Please fill the Amazon ID and Product Name of the BETA product into the field below:",
    AMAZON_ACCOUNT_IOSAPIKEY_NOTE: "Please enter the API Key you generated on the Amazon website here: ",
    AMAZON_ACCOUNT_ANDROIDAPIKEY_NOTE: "Please enter the API Key you generated on the Amazon website here:",
    AMAZON_ACCOUNT_NOTE_FILEDEMPTY: "This field shouldn't be empty.",
    AMAZON_ACCOUNT_NOTE_FILEDTOOLONG: "This field is too long.",
    AMAZON_ACCOUNT_NOTE_INVALIDFORMAT_IOS:
        "Invalid format. Please follow the document to check your action again, especially the Bundle Id field.",
    AMAZON_ACCOUNT_NOTE_INVALIDFORMAT_ANDROID:
        "Invalid format. Please follow the document to check your action again, especially the Package field.",
    AMAZON_ACCOUNT_NOTE_FINISH_NOTE: "Here's the information for PROJECT_ID_HOLDER, please confirm.",
    AMAZON_PROJECT_NEW: "New Project",
    AMAZON_PROJECT_EXIST: "This project has already been registered.",
    AMAZON_PROJECT_HINT: "Unique identifies your project, can only contain letters and numbers.",
    AMAZON_PROJECT_NAME_INVALID: "Project ID's format invalid.",
    AMAZON_PROJECT_NAME_TOO_SHORT: "Project ID too short.",
    AMAZON_PROJECT_NAME_TOO_LONG: "Project ID too long.",
    AMAZON_PROJECT_COMMENT_ERROR: "Comment cannot be empty.",
    AMAZON_ACCOUNT_CANCEL: "Cancel",
    AMAZON_ACCOUNT_PROJECT: "Project ID",
    AMAZON_ACCOUNT_AMAZONID: "Amazon ID",
    AMAZON_ACCOUNT_NEW_SECURITYPROFILE: "New Security Profile",
    AMAZON_ACCOUNT_CLIENTID: "Client ID",
    AMAZON_ACCOUNT_CLIENTSECRET: "Client Secret",
    AMAZON_ACCOUNT_AMAZONID_INVALID: "Amazon ID can only contain capitals and numbers.",
    AMAZON_ACCOUNT_CLIENTID_INVALID: "Client ID's format invalid.",
    AMAZON_ACCOUNT_CLIENTSECRET_INVALID: "Client Secret's invalid.",
    AMAZON_PRODUCT_OFFICIAL_ID: "Official Product",
    AMAZON_PRODUCT_BETA_ID: "Beta Product",
    AMAZON_PRODUCT_NEW_WAITING: "Hold on",
    WAITING_DIALOG_FINISH: "Operation finished",
    WAITING_DIALOG_WAITING: "Please wait",
    AMAZON_PROJECT_DOWNLOAD_NOTE: 'Please send the downloaded file "FILE_HOLDER" to us, thank you.',
    AMAZON_PROJECT_OPERATION: "Operations",
    AMAZON_PROJECT_BUILD: "Build",
    AMAZON_PROJECT_EDIT: "Edit",
    AMAZON_PROJECT_DOWNLOAD: "Download",
    AMAZON_PROJECT_INFO: "Info",
    AMAZON_PROJECT_NEXT: "Next",
    AMAZON_PROJECT_EDIT_NOTE:
        "Carefully to modify these information, keep these the same with the information generated from Amazon website, or the AVS would work abnormally.",
    AMAZON_ACCOUNT_NO_APPS: "You don't have any apps.",
    AMAZON_APP_NEW: "New App",
    AMAZON_APP_SELECT_PROJECT_NOTE: "Please choose which project belongs to:",
    AMAZON_APP_NAME: "App Name",
    AMAZON_APP_ICON: "App Icon",
    AMAZON_APP_ICON_DESC: "Size: 1024x1024 format: png",
    AMAZON_APP_LAUNCHIMAGE: "Launch Image",
    AMAZON_APP_LAUNCHIMAGE_1080P_DESC: "For normal phone; Size: 1242*2208",
    AMAZON_APP_LAUNCHIMAGE_IPAD_DESC: "For pad; Size: 1536*2048",
    AMAZON_APP_LAUNCHIMAGE_IPHONEX_DESC: "For iPhoneX; Size: 1125*2436",
    AMAZON_DEVICE_NAME: "Device Name",
    AMAZON_DEVICE_NAME_DESC: "Prefix or suffix, tells user to connect bluetooth device; for example Linkplay_XXX",
    AMAZON_APP_DEVICE_TYPE: "Device Type",
    AMAZON_APP_DEVICE_HINT: "Please choose your device type",
    AMAZON_APP_FINISH: "Finish",
    AMAZON_APP_BUILD_BETA: "Build For AVS Certification",
    AMAZON_APP_BUILD_BETA_BUSY: "Build For AVS Certification (building)",
    AMAZON_APP_BUILD_INVALID_NOTE: "Please check the information you entered.",
    AMAZON_APP_START_EDIT_WAITING: "The cloud is preparing for you, hold on.",
    SDK_DOWNLOAD: "Download",
    SDK_DOCUMENT: "Documents",
    SDK_LATEST_VERSION: "Latest Version",
    SDK_HISTORY_VERSION: "History Versions",
    SDK_NOT_PERMISSION: "You don't have permission to access this page; please contact PM to get more information.",
    MODIFY_CURRENT_PASS: "Current password",
    MODIFY_NEW_PASS: "New password",
    MODIFY_REPEAT_PASS: "Please enter new password again",
    MODIFY_PASS_CANCEL: "Cancel",
    MODIFY_PASS_CONFIRM: "Confirm",
    MODIFY_PASS_INVALID: "Password should should only contain letters and numbers and should between 6-16",
    MODIFY_PASS_NEW_REPEAT_NOTSAME: "This should be the same with the new password.",
    AMAZON_ACCOUNT_HELP: "Help",
    AMAZON_ACCOUNT_CHECK_PRODUCT_NOTE:
        "* If you have some issues with your product, you can check yourself with this document",
    AMAZON_PROJECT_RELEASE: "Edit Official APIKey",
    AMAZON_APIKEY_MANAGE: "APIKey Management",
    AMAZON_ACCOUNT_SECURITYPROFILE_NAME: "Security Profile Name",
    AMAZON_ACCOUNT_SECURITYPROFILE_ID: "Security Profile ID",
    PROJECTINIT_INIT_NOTE: "Please enter the following neccessary information to create your project.",
    PROJECTINIT_PROJECT_ID: "Project ID",
    PROJECTINIT_BT_NAME: "Bluetooth Name",
    PROJECTINIT_BT_HINT: "The name of the BT signal",
    PROJECTINIT_DEVICE_NAME: "Device Name",
    PROJECTINIT_DEVICE_HINT: "The name to distinguish the device",

    AMAZON_ACCOUNT_PRODUCT_BETA_NAME_INVALID:
        "Beta Product Name should ends with _BETA, you should check it on the Amazon web",
    AMAZON_ACCOUNT_PRODUCT_BETA_ID_INVALID:
        "Beta Product ID should be Official Product ID + _BETA, you should check it on the Amazon web",
    AMAZON_ACCOUNT_PRODUCT_INVALID: "Profile ID's format invalid.",
    AMAZON_ACCOUNT_FIRMWARE_INFO: "Firmware SDK Configuration",
    BACK: "Back",
    AMAZON_ACCOUNT_NOTE_BUNDLEID_INVALID: "Please use string like com.xxx.xxx",
    SUPPORT_SEARCHFIELD_HOLDER: "Enter your question here",
    SUPPORT_WELCOME_TEXT1: "How can we help you?",
    SUPPORT_WELCOME_TEXT2: "Ask us any question at all!",
    SUPPORT_FAQ_TITLE: "Frequently Asked Questions",
    PROJECT_TITLE_PROJECT: "Project Information",
    PROJECT_TITLE_PROJECT_BASIC: "Basic Information",
    PROJECT_TITLE_PRODUCT_DEFINE: "Product Specification",
    PROJECT_TITLE_PRODUCT_CATEGORY: "Product Category",
    PROJECT_TITLE_3P_SPEC: "Other Services",
    PROJECT_TITLE_SUBMIT: "Confirm",
    PROJECT_TITLE_REPULSE: "Reject",
    PROJECT_TITLE_MARKET_INFO: "Market Information",
    PROJECT_MARKET_TOOLESS: "Market information should more than 20 words",
    PROJECT_NOTE_FIX_WRONG_INPUT: "Please fix the incorrect fields.",
    PROJECT_NEW_VOICE_SERVICE: "Voice Service",
    PROJECT_VOICE_TRIGGER_WAY: "Trigger Way",
    PROJECT_NEW_MARKET_INFOHELPER: "Include brand descriptions, sales channels, sales forecast",
    PROJECT_DEVICE_DSPMODEL: "DSP Models",
    PROJECT_NEW_DSPSAMPLE: "DSP Sample Rate",
    PROJECT_NEW_DSPI2S: "DSP IIS",
    PROJECT_NEW_DSPOUTPUT: "DSP Output",
    PROJECT_NEW_OTHERMCU: "Other MCU",
    PROJECT_3PCERTIFICATE: "Third Party Certification",
    PROJECT_NEW_3PCERTIFICATE_NOTE:
        "Note, these certifications need extra cost, please contact your business contact for more information.",
    PROJECT_DEVICE_SIXSIDE: "Product Dimensions",
    PROJECT_NEW_SIXSIDE_SPEC: "At lease 1280x720 pixels",
    PROJECT_NEW_REQUIRED: "Required",
    PROJECT_NEW_TIME_NEED_TO_LATER_THAN_TODAY: "Date needs to be later than today",
    PROJECT_NEW_FIRST_MPCOUNT: "First batch shipments",
    PROJECT_NEW_CLIENT_COMPANY: "Client Company",
    PROJECT_NEW_CLIENT_BRAND: "Client Brand",
    PROJECT_NEW_CLIENT_CONTACT: "Client Contact",
    PROJECT_NEW_CLIENT_PHONE: "Client Phone",
    PROJECT_NEW_PRODUCT_MODEL: "Product Model",
    PROJECT_NEW_MARKET_ZONE: "Sales Territory",
    PROJECT_NEW_ODM_COMPANY: "ODM Company",
    PROJECT_NEW_ODM_PROJECT: "ODM Project",
    PROJECT_NEW_ODM_CONTACT: "ODM Contact",
    PROJECT_NEW_ODM_PHONE: "ODM Phone",
    PROJECT_NEW_AGENT: "Agent",
    PROJECT_NEW_AGENT_CONTACT: "Agent Contact",
    PROJECT_NEW_AGENT_PHONE: "Agent Phone",
    PROJECT_NEW_TESTMP_DATE: "Planned Trial Date",
    PROJECT_NEW_SAMPLE_DATE: "Prototype Machine Date",
    PROJECT_NEW_MP_DATE: "Planned Mass Product Date",
    PROJECT_NEW_NUMBER_FORMAT_NOTE: "Please enter correct number",
    PROJECT_NEW_BUSINESS_OFFICER: "Business Contact",
    PROJECT_NEW_NEXT_STEP: "Next",
    PROJECT_NEW_PREVIOUS_STEP: "Previous",
    PROJECT_NEW_MARKETZONE_TOO_MANY:
        "You can check most 3 territories, for more information please contact the business",
    PROJECT_NEW_IMAGE_SIZE_NOTE: "THe size of image isn't satisfy the requirement",
    PROJECT_NEW_AVS_TITLE: "AVS Product Information",
    PROJECT_NEW_AVS_FORM_TITLE: "Alexa Certification Document",
    PROJECT_NEW_PRODUCT_LINE: "Product Line",
    PROJECT_NEW_CLIENT_TITLE: "Client Information",
    PROJECT_NEW_ODM_TITLE: "ODM Information",
    PROJECT_NEW_AGENT_TITLE: "Agent Information",
    PROJECT_NEW_NAME_NO_CHINESE: "This information would provide to Amazon, please don't use Chinese",
    PROJECT_NEW_TIME_NEED_TO_LATER_THAN_2M: "Date needs to be later than 2 months",
    PROJECT_NEW_NO_NEED_3PINFO_NOTE: "Current product specification requires no more information.",
    PROJECT_NEW_PROJECT_SUMMARY: "Summary",
    PROJECT_NEW_VIEW_HELP_DOC: "Click here to view the help document",
    PROJECT_NEW_PROJECT_TITLE: "New Project",
    PROJECT_NEW_PROJECT_EDIT_TEMPLATE: "Edit Template",
    PROJECT_NEW_WIFISPEAKER: "Wi-Fi Speaker",
    PROJECT_DEVICE_MODEL: "Model",
    PROJECT_VOICE_TRIGGER_TOUCH: "Tap or click button",
    PROJECT_VOICE_TRIGGER_HANDSFREE: "Near field voice",
    PROJECT_VOICE_TRIGGER_FARFIELD: "Far field voice",
    PROJECT_NEW_PRODUCT_CATEGORY_BTSPEAKER: "Bluetooth Speaker",
    PROJECT_NEW_PRODUCT_CATEGORY_BTEARPHONE: "Bluetooth Earphone",
    PROJECT_NEW_PRODUCT_CATEGORY_CARLIGHTER: "Bluetooth Car Lighter",
    PROJECT_NEW_PRODUCT_NAME: "Product Name",
    PROJECT_NEW_IOT_SUPPORT: "Support IOT",
    PROJECT_NEW_FINAL_NOTE: "Your business contact is {0}, please wait for our review.",
    NAVBAR_SUPPORT_TIP: "Support",
    PROJECT_BASIC_INFO: "Basic Information",
    PROJECT_STATE_WAIT_REVIEW: "Waiting for review",
    PROJECT_STATE_IN_REVIEW: "In review",
    PROJECT_STATE_IN_DEVELOP: "In research",
    PROJECT_NEW_APP_DEVTYPE: "App Spec",
    PROJECT_NEW_APP_BASIC_CUSTOM: "App Customization",
    PROJECT_NEW_PROJECT_SUCCESS: "New project {0} success.",
    PROJECT_BACK_TO_LIST: "< Back to all Projects",
    PROJECT_SALES_GRETTING_NOTE:
        "Hi {0}, the following information is {1}'s request form, please check and fill in your comment at the page bottom:",
    PROJECT_SALES_OPERATE_NOTE: "Please fill the following fields:",
    PROJECT_SALES_COMMENT: "Sales Comment",
    PROJECT_SALES_COMMENT_HELPER:
        "Enter your comment to help making privilege and other permissions. This may include information about products count, price and other information.",
    PROJECT_INITPRIORITY: "Priority",
    PAGE_NOT_PERMISSION:
        "You don't have permission to access this page; please contact Administrator for more information.",
    PROJECT_SALES_OPERATE_SUCCESS: "Operation finished. PM {0} would take over the next step. Good job, thank you.",
    PROJECT_PM_OPERATE_SUCCESS: "Operation finished. Research {0} would take over the next step. Good job, thank you.",
    PROJECT_SALES_OPERATE_INVALID: "Operation failed, please contact the administrator.",
    PROJECT_NEW_CLIENT_EMAIL: "Client Email",
    PROJECT_TITLE_SOUND_OUTPUT_MODE: "Sound output mode",
    PROJECT_PRD_DOCUMENT: "Product Requirement Document",
    PROJECT_TITLE_IS_THERE_A_DISPLAY_SCREEN: "Is there a display screen",
    NO_DISPLAY_SCREEN: "no display screen",
    WITH_A_DISPLAY_SCREEN: "with a display screen",
    AMAZON_ACCOUNT_AVS_FORMAT_VERIFICATION: "This should be a mailbox. Please enter the correct format.",
    PROJECT_NEW_PROJECT_SKIP_TIP:
        "This is important information and skipping is not recommended. If not, please replenish as soon as possible.",
    PROJECT_NEW_PROJECT_SKIP: "Skip temporarily",
    PROJECT_NEW_PROJECT_FILL: "Continue to fill in",
    PROJECT_ALEXA_TECHNICAL_CONTACT_NOTE: "Client company contact",
    PROJECT_ALEXA_TECHNICAL_CONTACTMAIL_NOTE: "Client company contact email",
    PROJECT_ALEXA_REQUESTEDDATE_NOTE: "Please provide the requested test completion dates",
    PROJECT_ALEXA_DERIVATIVE_NOTE:
        "If you product is new designed, then you can ignore the following fields; otherwise you should fill in them.",
    PROJECT_NEW_WIFILIGHT: "Wi-Fi Light",
    PROJECT_REPULSE_TIPS:
        "There is a circular marking button {0} on the right side of each input item. If there is a problem with the input, the button can be marked as {1}, which can more accurately prompt the user to modify.",
    PROJECT_REJECTED_BY_PM_TIPS: "The project was rejected by PM {0} for the following reasons:",
    PROJECT_CHARGE_PM: "PM in Charge",
    PROJECT_TITLE_PROJECT_ESTABLISH: "Pass",
    PROJECT_PM_REVIEW_SUBMIT: "Submit",
    PROJECT_NEW_FIRMWARE_TITLE: "New Firmware Request",
};
